language: python
python:
  - "3.9"

env:
  - DJANGO_SETTINGS_MODULE=mysite.settings

before_install:
  - export DJANGO_SECRET_KEY=os.getenv("SECRET_KEY")

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source='.' manage.py test
  - coverage report

after_success:
  - coveralls