language: python
python:
  - "3.9"
  
env:
  - DJANGO_SETTINGS_MODULE=mysite.settings

before_install:
  - export DJANGO_SECRET_KEY='test-secret-key-for-ci'

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source='.' manage.py test
  - coverage report

after_success:
  - coveralls --verbose

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "djangotutorial"
  env: "swe1-app-env"
  bucket_name: "elasticbeanstalk-us-west-2-497589206040"
  on:
    branch: main